### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld_c#10]
![es2_20](https://cloud.githubusercontent.com/assets/3002194/20041037/1d8e754e-a463-11e6-92ba-34eac69ae030.jpg)

**Comment by CarloRuzzon** [comment]
cos'è %f e come faccio a dichiarare una costante?

**Comment by FabioZTessitore** [comment]
della costante non preoccuparti. 

%f è la specifica di stampa dei floating point

**Comment by CarloRuzzon** [comment]
prof ma mi escono le operazioni tutte sballate

2016-11-06 21:45 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
vediamo cosa hai fatto

**Comment by FabioZTessitore** [comment]
solo perché usi il C non devi dimenticare le cose fatte in Python.
Il raggio è un intero, ma i risultati sono tutti floating point, quindi attenzione quando scrivi le formule.
Infine quando stampi, se devi stampare floating point devi mettere %f e non %d

**Comment by CarloRuzzon** [comment]
controllate prof

Il giorno 6 novembre 2016 22:35, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
ok
