### ISSUE TITLE
tabella

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld_c#18]
![es2_31](https://cloud.githubusercontent.com/assets/3002194/20316358/c57c8e30-ab61-11e6-8e7b-8ed47608e020.jpg)

qui puoi usare una sola variabile

**Comment by FabioZTessitore** [comment]
ti ho mandato la mia versione per confronto (fai troppe printf)

adesso crea la repo "volo"

**Comment by CarloRuzzon** [comment]
Prof io comunque aspetto notizie precise per quanto riguarda il nuovo
problema

2016-11-21 21:12 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ti ho chiesto di creare la repo "volo"
