### ISSUE TITLE
HelloWorld

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld_c#2]
Scrivere un programma per la stampa della stringa
"Hello, World!" utilizzando **due** chiamate a printf()

**Comment by CarloRuzzon** [comment]
fatto

2016-11-06 18:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
haha va bene ma manca lo spazio dopo la virgola. Andiamo avanti
