### ISSUE TITLE
Stampa Scacchiera

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld_c#5]
![es2_27](https://cloud.githubusercontent.com/assets/3002194/20040065/f3bfb5c8-a450-11e6-9fe1-a3a3e51f8b8e.jpg)

**Comment by CarloRuzzon** [comment]
finish

2016-11-06 18:44 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
per evitare queste stringhe così lunghe puoi fare così:

``` C
printf("stringa lunga, la posso chiudere\n"
    " e riaprire ...\n");
```

**Comment by CarloRuzzon** [comment]
okay

2016-11-06 20:26 GMT+01:00 Fabio Z Tessitore notifications@github.com:
