### ISSUE TITLE
limiti delle variabili

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld_c#8]
sai qualcosa sui valori minimo e massimo per i vari tipi di variabili?

**Comment by CarloRuzzon** [comment]
Si ma non a memoria e non li ricordo bene

**Comment by FabioZTessitore** [comment]
ok
se includi il file limits.h puoi stampare i valori INT_MIN e INT_MAX
prova

**Comment by FabioZTessitore** [comment]
fai un pull, ho modificato la repo aggiungendo il file somma.c

**Comment by CarloRuzzon** [comment]
perfetto

2016-11-06 20:52 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by CarloRuzzon** [comment]
ve lo devo pushare?

2016-11-06 20:59 GMT+01:00 carlo ruzzon carloruzzon@gmail.com:

**Comment by FabioZTessitore** [comment]
sarebbe bello

**Comment by CarloRuzzon** [comment]
hahaha

2016-11-06 21:00 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by CarloRuzzon** [comment]
fatto

2016-11-06 21:01 GMT+01:00 carlo ruzzon carloruzzon@gmail.com:

**Comment by FabioZTessitore** [comment]
va bene, ce lo potevi mettere un newline haha

quando puoi ci sono gli esercizi
