### ISSUE TITLE
operazioni

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld_c#9]
![es2_16](https://cloud.githubusercontent.com/assets/3002194/20041034/0db60ba0-a463-11e6-8a58-4803f558c24c.jpg)

**Comment by CarloRuzzon** [comment]
fatto

2016-11-06 20:53 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
sempre queste stringhe lunghissime
